Hw 08 done
smirnov-i-SPbAU/JavaPractice pull request #10
Opened 2019-04-27 22:45 UTC by smirnov-i-SPbAU

2019-05-13 09:48 UTC, yurii-litvinov requested changes

2019-05-13 09:48 UTC, yurii-litvinov commented on 190426_threadpool/src/main/java/ru/spbhse/smirnov/threadpool/ThreadPoolImpl.java
> +        public synchronized T get() throws LightExecutionException, InterruptedException {
Это слишком пессимистично. Гонка ведь возможна только в случае, если результат ещё не готов, а тут обращения к get синхронизируются вообще всегда.

2019-05-13 09:48 UTC, yurii-litvinov commented on 190426_threadpool/src/main/java/ru/spbhse/smirnov/threadpool/ThreadPoolImpl.java
> +        for (Thread thread : threads) {
А если прямо вот в это время сделают submit()?

2019-05-13 09:48 UTC, yurii-litvinov commented on 190426_threadpool/src/test/java/ru/spbhse/smirnov/threadpool/TaskQueueTest.java
> +    void runManyСonsumersAndProductors(int consumersCounter, int productorsCounter) throws InterruptedException, TimeoutException {
producers?

2019-05-13 09:48 UTC, yurii-litvinov commented on 190426_threadpool/src/test/java/ru/spbhse/smirnov/threadpool/TaskQueueTest.java
> +            final Waiter waiter = new Waiter();
var?

2019-05-13 09:48 UTC, yurii-litvinov commented on 190426_threadpool/src/test/java/ru/spbhse/smirnov/threadpool/TaskQueueTest.java
> +            Thread[] threads = new Thread[consumersCounter + productorsCounter];
var?

2019-05-15 08:30 UTC, smirnov-i-SPbAU commented on 190426_threadpool/src/main/java/ru/spbhse/smirnov/threadpool/ThreadPoolImpl.java
> +        for (Thread thread : threads) {
Если во время исполнения 83 строки, то, кажется, все будет хорошо. shutdown флаг к тому моменту true, и пользователь схватит исключение.
Но выше, действительно, есть проблема, если submit() сделаю во время wait (не гарантируется, что второй поток увидит изменение в shutdownFlag). Это поправлю.

2019-06-09 11:35 UTC, yurii-litvinov approved these changes
Да, вот теперь вроде всё ок. Зачтена

2020-01-31 09:30 UTC, merged